# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import n_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=255, null=True, upload_to=n_profile.models.user_directory_path)),
                ('photo_350', models.ImageField(max_length=255, null=True, upload_to=n_profile.models.user_directory_path)),
                ('photo_40', models.ImageField(max_length=255, null=True, upload_to=n_profile.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
